### ISSUE TITLE
能否在readme里给一份方法使用的示例代码

### ISSUE THREAD

**Issue by dnslin** [Shimada666/super-stream#1]
例如 for_each 就不大同于 java中的foreach()，也可能是我刚写python 没理解清楚 ，麻烦了

**Comment by Shimada666** [comment]
for_each 怎么不同呢，之前知乎也有人提过这个问题，可否给个样例

**Comment by dnslin** [comment]
![image](https://user-images.githubusercontent.com/49158572/185743355-0d8b9738-eadb-48f8-8c3b-e06d76210e6e.png)
例如这里我想将 下面已经用for实现的操作 用 Stream去实现我不知道如何去下手

但是 java
就可以 list.foreach(e->{
       xxxxx.xxxx = result.xxxx
})
我大概意思就是这样

**Comment by dnslin** [comment]
同时也感谢您实现这个库，已star

**Comment by Shimada666** [comment]
> ![image](https://user-images.githubusercontent.com/49158572/185743355-0d8b9738-eadb-48f8-8c3b-e06d76210e6e.png) 例如这里我想将 下面已经用for实现的操作 用 Stream去实现我不知道如何去下手
> 
> 但是 java 就可以 list.foreach(e->{ xxxxx.xxxx = result.xxxx }) 我大概意思就是这样

我这实现的是 java stream  的 forEach方法，对标的是 list.stream().forEach(xxxxx)，你的 list.forEach 是 List 的 forEach 接口...

**Comment by dnslin** [comment]
可以的话 还是麻烦您 书写一个 完整 example 放到readme方便使用者快速上手

**Comment by Shimada666** [comment]
> 可以的话 还是麻烦您 书写一个 完整 example 放到readme方便使用者快速上手

可以，我搞个文档

**Comment by Shimada666** [comment]
搞了个简单的，还在完善用例中

[shimada666.github.io/super-stream/](https://shimada666.github.io/super-stream/)

**Comment by dnslin** [comment]
thanks

**Comment by zq46** [comment]
> ![image](https://user-images.githubusercontent.com/49158572/185743355-0d8b9738-eadb-48f8-8c3b-e06d76210e6e.png) 例如这里我想将 下面已经用for实现的操作 用 Stream去实现我不知道如何去下手
> 
> 但是 java 就可以 list.foreach(e->{ xxxxx.xxxx = result.xxxx }) 我大概意思就是这样

在流式操作中修改一个已经存在的 list 可能不太好。
可以试下：
```python
result_list = (
    Stream(source_list)
    .map(lambda event : {'title': event['title'], 'description': event['description'], 'display_url': event['display_url'], 'end_date': event['end_date']})
    .to_list()
)
```
先把 source_list 里的每个 event 映射到需要的格式，再用 to_list 收集为 list 并赋给 result_list 。

**Comment by dnslin** [comment]
> > ![图片](https://user-images.githubusercontent.com/49158572/185743355-0d8b9738-eadb-48f8-8c3b-e06d76210e6e.png)例如这里我想将在下面已经用实现的操作流去实现我不知道如何去下手
> > java java list.foreach(e->{ xxxxx.xxxx = result.xxxx }) 我大概英文可能就是这样
> 
> 在式操作中修改了一个可能已经存在的列表。 可以试下：
> 
> ```python
> result_list = (
>     Stream(source_list)
>     .map(lambda event : {'title': event['title'], 'description': event['description'], 'display_url': event['display_url'], 'end_date': event['end_date']})
>     .to_list()
> )
> ```
> 
> 先把 source_list 中的每个事件映射到需要的格式，再用 to_list 收集为 list 并赋给 result_list 。
感谢， 在@岛田666 示例完成之前 我自己突然意识到这样写了 属于开窍了 哈哈

**Comment by Shimada666** [comment]
如果确实需要改字典或对象的值，也可以像这样 

```python
from superstream import Stream

const_var = 'updated!'

dict_list = [
    {
        'key1': 'value1',
        'key2': 'value2',
    }
]


def _update_dict(x):
    x['key1'] = 'updated!'


Stream(dict_list).for_each(_update_dict)

print(dict_list)

```

如果使用 @zq46 重新赋值返回新dict的方法，也有一些问题。比如一是将来字典结构变了之后，返回的字典内容也需要跟着变。二是代码较多。因此我感觉在 for_each 去修改对象或者字典本身的值也是合理的

**Comment by zq46** [comment]
> > 先把 source_list 中的每个事件映射到需要的格式，再用 to_list 收集为 list 并赋给 result_list 。
> 
> 感谢， 在@岛田666 示例完成之前 我自己突然意识到这样写了 属于开窍了 哈哈

哈哈，我也是这样过来的，写着写着就改进了。
了解到函数式编程后，意识到这就是其中函数无副作用的要求。

你原本的思路，是因为 Java 中的 lambda 匿名函数可以有多行，
而 python 的 lambda 匿名函数主体只能用一个表达式，所以没法用，
像 @Shimada666 说的定义一个处理 event 和结果 list 的函数传给 for_each  就可以了。

另外
``` python
lambda event : {'title': event['title'], 'description': event['description'], 'display_url': event['display_url'], 'end_date': event['end_date']}
```
这里也可以流式化
``` python
lambda event : Stream(['title', 'description', 'display_url', 'end_date']).to_map(lambda x : x, lambda x : event[x])
```

如果提前定义好属性列表和 identity 函数，
再把得到 source_list 和处理 source_list 的流连起来，
这段代码就一流到底了：
``` python
parsed_json = json.loads(result_json)['results']

attrs = ['title', 'description', 'display_url', 'end_date']

identity = lambda x : x

result_list = (
    Stream(parsed_json)
    .map(operator.itemgetter('_source'))
    .map(lambda event : Stream(attrs).to_map(identity, event.get))
    .to_list()
)
```
哈哈，最近我用 stream 用得很多，能 stream 化的都想把它 stream 化。
当然实际使用还是得考虑性能和可读性。

**Comment by Shimada666** [comment]
> > > 先把 source_list 中的每个事件映射到需要的格式，再用 to_list 收集为 list 并赋给 result_list 。
> > 
> > 
> > 感谢， 在@岛田666 示例完成之前 我自己突然意识到这样写了 属于开窍了 哈哈
> 
> 哈哈，我也是这样过来的，写着写着就改进了。 了解到函数式编程后，意识到这就是其中函数无副作用的要求。
> 
> 你原本的思路，是因为 Java 中的 lambda 匿名函数可以有多行， 而 python 的 lambda 匿名函数主体只能用一个表达式，所以没法用， 像 @Shimada666 说的定义一个处理 event 和结果 list 的函数传给 for_each 就可以了。
> 
> 另外
> 
> ```python
> lambda event : {'title': event['title'], 'description': event['description'], 'display_url': event['display_url'], 'end_date': event['end_date']}
> ```
> 
> 这里也可以流式化
> 
> ```python
> lambda event : Stream(['title', 'description', 'display_url', 'end_date']).to_map(lambda x : x, lambda x : event[x])
> ```
> 
> 如果提前定义好属性列表和 identity 函数， 再把得到 source_list 和处理 source_list 的流连起来， 这段代码就一流到底了：
> 
> ```python
> parsed_json = json.loads(result_json)['results']
> 
> attrs = ['title', 'description', 'display_url', 'end_date']
> 
> identity = lambda x : x
> 
> result_list = (
>     Stream(parsed_json)
>     .map(operator.itemgetter('_source'))
>     .map(lambda event : Stream(attrs).to_map(identity, event.get))
>     .to_list()
> )
> ```
> 
> 哈哈，最近我用 stream 用得很多，能 stream 化的都想把它 stream 化。 当然实际使用还是得考虑性能和可读性。

很好的代码！只是在第二个 map 的时候可读性稍微有些不够好。这段代码本质上应该是对象之间的转换，是多属性对象到少属性对象之间的转换。像 java 中可能会用 mapstruct 或者 bean copy 之类的工具处理，在 python 中，其实感觉复杂点可以考虑用 marshmallow 或者 pydantic 之类的做对象转换，将json读入的对象序列化成对象列表，再输出较少字段的对象列表。简单点直接像 @zq46 
https://github.com/Shimada666/super-stream/issues/1#issuecomment-1236401013 这样做应该就足够了，保证了代码简洁性与可读性

**Comment by Shimada666** [comment]
你好！可以的，for_each 方法接收一个函数，在函数中你可以修改 dict 的值。这是项目文档，目前还在完善中，有一些基本使用方法。https://shimada666.github.io/super-stream/

回到你说的这个问题。由于 python 的 lambda 函数比较孱弱（python设计师故意为之），使得 lambda 函数似乎无法实现对字典，或者对象，进行修改值的操作。因此此操作只能写一个实名函数进行赋值。
例子：



输出：
[{'key1': 'updated!', 'key2': 'value2'}]


后续有问题可以在 issue 中提出，谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月5日(星期一) 凌晨3:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Shimada666/super-stream] 能否在readme里给一份方法使用的示例代码 (Issue #1)



 例如这里我想将 下面已经用for实现的操作 用 Stream去实现我不知道如何去下手
 但是 java 就可以 list.foreach(e-&gt;{ xxxxx.xxxx = result.xxxx }) 我大概意思就是这样
  在流式操作中修改一个已经存在的 list 可能不太好。
 可以试下：
 result_list = ( Stream(source_list) .map(lambda event : {'title': event['title'], 'description': event['description'], 'display_url': event['display_url'], 'end_date': event['end_date']}) .to_list() )

 先把 source_list 里的每个 event 映射到需要的格式，再用 to_list 收集为 list 并赋给 result_list 。
