### ISSUE TITLE
功能建议： starmap

### ISSUE THREAD

**Issue by zq46** [Shimada666/super-stream#10]
类似于 itertools.starmap 和 multiprocessing.starmap 的方法。

时常会遇见需要写`Stream(zip(iterable_a, iterable_b)).map(lambda x : func(*x))`的情况，
如果有 starmap 就可以写成`Stream(zip(iterable_a, iterable_b)).starmap(func)`，简短直观一些。
不知道特意增加个 starmap 是否适合？

**Comment by Shimada666** [comment]
可以呀，你提个 pr 吧，回头我再把文档完善下，少写一段 lambda x 确实不错
