### ISSUE TITLE
Bug report: 当流包含不同类型元素时，reduce 行为与 functools.reduce 不一致。

### ISSUE THREAD

**Issue by zq46** [Shimada666/super-stream#11]
如`functools.reduce(lambda a,b:a+b, [1,2,‘a’])`会报错提示：
`TypeError: unsupported operand type(s) for +: 'int' and 'str'`

而`Stream([1,2,'a']).reduce(lambda a,b:a+b)`结果为None，无提示。

要纠正这个 Bug 且继续支持对空流的 Optional 结果返回，
可能需要直接修改使用 functools.reduce 的代码：
https://github.com/python/cpython/blob/3.10/Lib/functools.py#L232

**Comment by Shimada666** [comment]
感谢反馈！确实是个 bug，你能提个 pr 修复它吗，我会很快合并的。

**Comment by zq46** [comment]
又仔细思考了下，我现在没有什么好的修复方法，因为下面列出的一些考虑。你可以参考下，看看有没有什么比较好的方法。

出现这个 bug 的原因是： functools.reduce 在没有 initial 且 iterable 为空时也是报的 TypeError 错误，因此 Stream.reduce 在没有 initial 且出现 TypeError 错误时返回 None 以支持对空流的 Optional 结果返回，但这掩盖了原帖例子里的报错。

1. 如果还是直接使用 functools.reduce 函数来实现 Stream.reduce 方法。我想不到什么方法来修复这个 bug，这需要区分这两种 TypeError。要么放弃对 Optional 结果的支持，都报错。

2. 我上面提到 Stream.reduce 可以直接修改使用 functools.reduce 的代码。这样做虽然可以，但是会有性能损失。因为 functools.reduce 首先尝试导入 C 编写的模块，导入失败才会使用纯 python 模块。如果 Stream.reduce 直接修改使用纯 python 模块 reduce 的代码，那就不会利用到 C 模块 reduce 的性能。

所以这块可能需要仔细考虑下。

**Comment by zq46** [comment]
修复了！
