### ISSUE TITLE
reduce空列表和0初始值

### ISSUE THREAD

**Issue by ldxm9527** [Shimada666/super-stream#2]
你好！感谢提供的Stream工具，非常好用！
在使用过程中遇到一个问题，不确定是否是bug，所以提问。
输入：Stream([]).reduce(lambda x, y: x + y, 0)
输出：TypeError: reduce() of empty sequence with no initial value
因为在reduce中，initial参数值，0与None是相同语义，会被判定为未提供initial，走else分支。
预期是在操作空列表时，提供0初始值仍然可以返回0；但是按目前的代码每次都要判断空列表稍显麻烦。

**Comment by Shimada666** [comment]
你好！前几周发布的 0.2.1 版本注意到了此问题，在 0.2.1 版本中，Stream([]).reduce(lambda x, y: x + y, 0) 会返回 None。但似乎行为仍与 java 不符
```java
List<Integer> a = new ArrayList<>();
System.out.println(a.stream().reduce(0, (x, y) -> x + y));;
```
我认为这是一个 bug，我稍后看一下，之后应该会在今天之内发布 0.2.2 版本对齐 java 的行为。感谢反馈

**Comment by ldxm9527** [comment]
reduce中的if initial在python中对[], {}, ""有歧义，建议改成if initial is None严格判断是否为None。
PS：我和小伙伴们纷纷对大佬深厚的python（以及java）功底表示钦佩XD

**Comment by Shimada666** [comment]
> reduce中的if initial在python中对[], {}, ""有歧义，建议改成if initial is None严格判断是否为None。 PS：我和小伙伴们纷纷对大佬深厚的python（以及java）功底表示钦佩XD

已发布 0.2.2 版本，修复了这个问题，可以升级下版本
