### ISSUE TITLE
count 方法求序列长度的内存消耗

### ISSUE THREAD

**Issue by zq46** [Shimada666/super-stream#4]
#### 内存占用

现在 super-stream 中的代码是 O(n) 时间和 O(n) 内存的。
``` python
    def count(self) -> int:
        return len(list(self._stream))
```

我要处理的 iterable 中每个 element 都是从磁盘文件中顺序读取并处理的，而且比较大，所以转为 list 再计数就太占内存了。

所以我开始是使用 `.map(lambda x : 1).sum()` 来避免内存占用的，后来发现 more_itertools 包里有 O(1) 内存的最快实现：
``` python
def ilen(iterable):
    counter = count()
    deque(zip(iterable, counter), maxlen=0)
    return next(counter)
```
需要的时间大约是 `len(list(iterable))` 的 5 倍。

个人感觉对 iterable 而言，占用 O(1) 内存的计数方法更合理。

而且如果这两个方法的时间差大到可以轻易感知，那么 stream 对象转为 list 占用的内存已经不小了。

##### count

这个方法的名字用 count 感觉不是很合适：
list 等类型的 count 是用来计算包含特定对象的个数；
itertools 中的 count 用来生成计数迭代器；
collections 中有个 Counter 类提供了可哈希对象的计数功能。

在 numpy 中是用 size 的，但是对于 iterable 序列而言 length 好像比 size 合适。

最后感觉还是 more_itertools 中用的 ilen 比较合适：
(1) 函数 len 在 python 中比较通用，但 iterable 的 length 需要 O(n) 时间，不像 len 是 O(1) 的。
(2) 用 ilen 表明是求 iterable 的 length 。

---

##### to_map

另外在 python 中用 to_dict 可能比 to_map 合适点，或者两个都留着。

---

一点个人的看法供参考。

**Comment by Shimada666** [comment]
感谢你的建议！
### 性能
关于 count 性能的建议很好！当时只是为了最快写出一个能用的原型。我刚看了 java 中的实现，是转 longstream 后求 sum。这与你 `.map(lambda x : 1).sum()` 的方式不谋而合。这里使用 ilen 也是可以的。可以测试一下哪个性能更好么？我们可以选择一个性能最好的版本。你可以就此提一个 PR 吗？
```java
@Override
public final long count() {
    return mapToLong(e -> 1L).sum();
}
```
### 函数名
count 名是直接一直的 stream 的 count 方法，对标的就是 java 中 xx.stream().count()，用来获得流中的数量，这个 api 应该是不会再变了。

### to_map 
这个函数是直接移植 .collect(Collectors.toMap()) 的，我前面在思考能不能把 Collectors 这一套也抄过来，因为 joining 等方法也是必要的，而且这对类型提示可能也比较友好。
在这之前我觉得将 to_map 改名 to_dict，然后将 to_map 重定向过去也是很好的。这块也欢迎 PR

**Comment by zq46** [comment]
感谢采纳！

我测试过 ilen 更快。

这是 more-itertools 包中 ilen 的[代码](https://github.com/more-itertools/more-itertools/blob/master/more_itertools/more.py#L485)与[讨论](https://github.com/more-itertools/more-itertools/pull/236)。

stackoverflow 上已经有一个[详细的测试](https://stackoverflow.com/questions/3345785/getting-number-of-elements-in-an-iterator-in-python/65552740#65552740)：
其中 iteration_utilities 包中的方法最快，与 len(list(iterable)) 相当，但是他是用 C 实现的。
只使用 python 标准库实现，more-itertools  用 counter 和 deque 实现的 ilen 最快。

我稍后提交 PR 。

**Comment by Shimada666** [comment]
#5 已合并！发布了新版本 0.2.3，已经可以使用了。感谢你的贡献！

**Comment by Shimada666** [comment]
> 多谢采纳！ to_map 和 to_dict 是各自实现？还是把 to_dict 重定向 to_map？或是反过来？ 我待会提交 PR

我想可以将 to_dict 作为默认实现，to_map 作为 to_dict 的别名。既然是 python 了，还是要以 python 的类型为基础。

**Comment by zq46** [comment]
我还是建议把 count 改为 ilen，或者将其作为 ilen 的别名。
毕竟这里的 count 与 python 里众多类型的 count 方法逻辑不一致。
当然，我想的可能不周全。你再仔细考虑下，怎么比较合适。

**Comment by Shimada666** [comment]
> 我还是建议把 count 改为 ilen，或者将其作为 ilen 的别名。 毕竟这里的 count 与 python 里众多类型的 count 方法逻辑不一致。 当然，我想的可能不周全。你再仔细考虑下，怎么比较合适。

感谢建议！我理解你的想法。因为我一开始只想在 python 中复刻一下 java stream。而你 collect 的思路 #3 启发了我，我们确实可以依赖 python 的特性，做一些 java 没有的功能。确实，在 python 中，count 确实容易造成歧义，我有以下想法

1. 如果直接将 count 更名为 ilen，会是一个破坏性变更，可能会影响一些已经在使用这个库的人。
2. java stream 中就叫 count ，名字不对齐，可能有一些学习成本。如果今后有别的方法叫 count，会极大增加学习成本「为什么 python 的 count 方法行为与 java 的不一致」

因此，我考虑可能可以新增一个方法 ilen，返回流中的元素的个数。而原先的 count 作为 ilen 的别名。使用时推荐使用 ilen。你认为怎么样呢？

**Comment by zq46** [comment]
嗯，我感觉这样处理比较好，以后有新的想法的话，变动影响会小一些。

**Comment by zq46** [comment]
你来增加 ilen 方法吧。我已经 commit 了 collect 方法，等 commit collects 方法后一起 PR 。

**Comment by Shimada666** [comment]
> 你来增加 ilen 方法吧。我已经 commit 了 collect 方法，等 commit collects 方法后一起 PR 。

ok，ilen 感觉并不够直观，我打算直接写为 len 方法？或者 size？这个我也没想好

**Comment by zq46** [comment]
> > 你来增加 ilen 方法吧。我已经 commit 了 collect 方法，等 commit collects 方法后一起 PR 。
> 
> ok，ilen 感觉并不够直观，我打算直接写为 len 方法？或者 size？这个我也没想好

嗯，ilen 是有点不直观。
不要用 len ，内置的 len 时间是 O(1) 的。
没去了解其他包的 size 时间复杂度多少，numpy 的size 应该是 O(1) 的。
要不就还是用 count ，我看到有不少包也是用的 count ，既然本打算留着 count ，那就还是用它吧。
而且一看名字就知道是 O(n) 时间的。

**Comment by Shimada666** [comment]
> > > 你来增加 ilen 方法吧。我已经 commit 了 collect 方法，等 commit collects 方法后一起 PR 。
> > 
> > 
> > ok，ilen 感觉并不够直观，我打算直接写为 len 方法？或者 size？这个我也没想好
> 
> 嗯，ilen 是有点不直观。 不要用 len ，内置的 len 时间是 O(1) 的。 没去了解其他包的 size 时间复杂度多少，numpy 的size 应该是 O(1) 的。 要不就还是用 count ，我看到有不少包也是用的 count ，既然本打算留着 count ，那就还是用它吧。 而且一看名字就知道是 O(n) 时间的。

这里的 len 是指方法名了，不是实现的方法。
用 count 也行，那这块就先不动把

**Comment by zq46** [comment]
> > > > 你来增加 ilen 方法吧。我已经 commit 了 collect 方法，等 commit collects 方法后一起 PR 。
> > > 
> > > 
> > > ok，ilen 感觉并不够直观，我打算直接写为 len 方法？或者 size？这个我也没想好
> > 
> > 
> > 嗯，ilen 是有点不直观。 不要用 len ，内置的 len 时间是 O(1) 的。 没去了解其他包的 size 时间复杂度多少，numpy 的size 应该是 O(1) 的。 要不就还是用 count ，我看到有不少包也是用的 count ，既然本打算留着 count ，那就还是用它吧。 而且一看名字就知道是 O(n) 时间的。
> 
> 这里的 len 是指方法名了，不是实现的方法。 用 count 也行，那这块就先不动把

嗯，明白。
我是想说：一般用的 len 和 size 是 O(1) 时间的，stream 这里的方法是 O(n) 时间的，就不好用这两个名字。所以那就还是 count 合适。
