### ISSUE TITLE
是否可以给 to_dict 方法 k, v 参数设置默认值？

### ISSUE THREAD

**Issue by zq46** [Shimada666/super-stream#8]
经常要写 `to_dict(operator.itemgetter(0), operator.itemgetter(1))`，
或者说是 `to_dict(lambda x : x[0], lambda x : x[1])`，
来将二元组的序列转为字典。这种场景可能是最常见的。

如果给 k, v 设默认值 `operator.itemgetter(0)` 和 `operator.itemgetter(1)` 可能会方便很多。
其他情况也可以先 `map` 到二元组，再 `to_dict()` 即可，或者还按以前方式也行。

望考虑。

**Comment by Shimada666** [comment]
感觉并没有啊，说实话我在 java 中最常见的是 to_map(XX::getId, Function.identity())，也就是转成一个 id -> self 的map，所以感觉这个可能不会加，不过用户可以继承他自己拓展

**Comment by zq46** [comment]
嗯，我后来想了一下。
正好得到一个二元组再转 dict 的场景应该是不多。
而且可以用 `.collect(dict)` 就行。
